# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cf0de9606a49052bd5c94b803f5b9afc0448b39513344b174a7ccb19d7f36040b4db04d96d60180597bb6ed140eb53ba24c594fffab6892bf76121fcfcd7d8

test:
  secret_key_base: 6a1d791c1c86bcb5f1a8c74bfdf917db2bf0a3a8108e4fc8cbffe125b3a10233d6183e73bfd018864fbed099662bfca56addd2398b8dfa304f1d4b0ae804e1f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
